window.TDC_CRM_SEED = [
  {
    "lead_id": "TDC2026-001",
    "program_year": 2026,
    "company": "Chap Mei Plastic Toys Manufactory Ltd",
    "chinese_name": "",
    "industry_group": "玩具/教育玩具",
    "product_category": "玩具模型",
    "brand": "CM / 集美玩具",
    "contact": "Jeffery Lam",
    "title": "Director",
    "email": "jefferylam@chapmei.com",
    "phone": "2756 0185",
    "website": "www.chapmei.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "抖音: 集多美玩具模型企業店；淘寶/天貓: 集多美玩具模型企業店",
    "start_time": "2024 年 5 月",
    "target_customer": "上班族、父母、寶媽",
    "pain_points": "廠家多、產品多。; 消費者選擇範圍大。; 競爭壓力大。; 七天無理由退貨，消費者退貨率高。",
    "needs": "做好品牌店。; 做消費者信賴的網店。; 培養消費者忠誠度。; 提升店舖銷售業績。; 學習電商運營基本功及流程。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "銷售額、轉化率、退貨率、投放成本、內容成本、主要 SKU。",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC_11家公司總結_及_問卷已填資料全集.md",
    "source_confidence": "High",
    "consulting_expectations": "",
    "story_selling_points": "情景玩具，培養兒童動手動腦能力，提高兒童專注力。"
  },
  {
    "lead_id": "TDC2026-002",
    "program_year": 2026,
    "company": "FritzS Learning (Hong Kong) Limited",
    "chinese_name": "",
    "industry_group": "玩具/教育玩具",
    "product_category": "教育玩具",
    "brand": "FritzS Learning",
    "contact": "Peri Chow / Peri",
    "title": "",
    "email": "peri.chow@fritzslearning.com",
    "phone": "6072 2650",
    "website": "www.fritzslearning.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "淘寶/天貓: FritzS 旗艦店；京東/京東國際: FritzS 旗艦店；小紅書商城: FritzS",
    "start_time": "2019",
    "target_customer": "幼稚園、幼兒教育中心、入口玩具商",
    "pain_points": "內捲。; 價格戰影響利潤。",
    "needs": "刺激銷售。; 增加教育品牌知名度。; 實際策略增加生意額及利潤。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "具體銷售額、毛利、廣告投放、主推 SKU、競品。",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC_11家公司總結_及_問卷已填資料全集.md",
    "source_confidence": "High",
    "consulting_expectations": "",
    "story_selling_points": "鼓勵成人與孩子一起玩，建立親子連結，simple play, simple life, colorful memories for childhood。"
  },
  {
    "lead_id": "TDC2026-003",
    "program_year": 2026,
    "company": "I-Had Creation Limited",
    "chinese_name": "",
    "industry_group": "玩具/教育玩具",
    "product_category": "積木玩具",
    "brand": "俐智（LOZ）",
    "contact": "Mandy Chim",
    "title": "Marketing Executive",
    "email": "mandychim@i-hadcreation.com",
    "phone": "3153 2533",
    "website": "www.loz-mini.com",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "",
    "start_time": "17/12/2025",
    "target_customer": "18-40 歲人士",
    "pain_points": "成立公司。; 中國大陸稅務。; 倉庫人手。",
    "needs": "自主開發一系列有關香港特色、內地電商沒有的產品。; 增加差異化及獨特性。; 了解更多在中國大陸營運電商的規則。; 了解成立公司及稅務相關事項。",
    "service_segment": "A2 從零入場/開店搭建",
    "recommended_services": "合規/跨境入場路線；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 4,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "90-Day Market Entry Sprint",
    "email_subject": "跟進香港好物節諮詢：90日內地電商入場方案",
    "personalization_hook": "您目前處於準備或剛入場階段，重點是先選對主推SKU、平台和最低可行測試預算。",
    "cta_next_action": "安排20分鐘確認主推SKU、入場方式和預算，我們可整理一版90日路線圖。",
    "missing_data": "現有銷售數據、平台計劃、預算、SKU 優先級。",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC_11家公司總結_及_問卷已填資料全集.md",
    "source_confidence": "High",
    "consulting_expectations": "",
    "story_selling_points": "以微型積木作賣點，多場景建築，注重細節。"
  },
  {
    "lead_id": "TDC2026-004",
    "program_year": 2026,
    "company": "Camenae Asia Company Limited",
    "chinese_name": "",
    "industry_group": "酒類",
    "product_category": "葡萄酒為主",
    "brand": "Chateaux Famaey、Kapelle、Schomehl、Winzerset、Latium、精葡",
    "contact": "Chrisce Lee",
    "title": "Director",
    "email": "clee@camehk.com",
    "phone": "9197 9694",
    "website": "www.camehk.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "京東/京東國際: abc store / Chateau Famaey",
    "start_time": "計劃 2026 年重點發展",
    "target_customer": "Wine Lovers",
    "pain_points": "Cost effective。; Customer education。; Loyalty。; Segmentation。; 需要用 low budget 有效推廣。",
    "needs": "Expand customer base。; Cultivate loyalty。; Sales & loyalty。; Advice on how to spend effectively with low budget。",
    "service_segment": "C1 先補KYC資料",
    "recommended_services": "合規/跨境入場路線；私域/CRM/復購",
    "data_completeness": "Low",
    "data_score": 1,
    "stage_score": 5,
    "fit_score": 2,
    "urgency_score": 3,
    "outreach_status": "KYC Required",
    "campaign": "KYC First Qualification",
    "email_subject": "跟進香港好物節諮詢：先補齊產品與渠道資料",
    "personalization_hook": "目前資料不足，先補齊產品、渠道、合規和預算後，策略會更準確。",
    "cta_next_action": "回覆主推SKU、價格、目標客群、現有渠道和90日預算即可開始分流。",
    "missing_data": "最新渠道狀態、銷售數據、年度目標、預算、小程序用途、是否已有內地供應鏈 / 酒類合規安排。；價格/毛利/庫存；現有渠道與銷售數據；90日測試預算",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC_11家公司總結_及_問卷已填資料全集.md",
    "source_confidence": "Medium",
    "consulting_expectations": "",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2026-005",
    "program_year": 2026,
    "company": "Fortune Pharmacal Limited",
    "chinese_name": "",
    "industry_group": "食品飲品",
    "product_category": "藥品及保健品",
    "brand": "幸福醫藥 / 幸福寳",
    "contact": "Gloria Tsui",
    "title": "Product Manager",
    "email": "gloria.tsui@fortunepharm.com",
    "phone": "852 9370 2608",
    "website": "https: / www.fortunepharm.com",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "京東/京東國際: 幸福醫藥海外京東自營店；微信: 香港幸福醫藥；抖音: 保健品計劃中",
    "start_time": "藥品 / 現有內地電商：2021 是次諮詢重點保健品：暫時未上架 / 計劃中",
    "target_customer": "所有人 / 都市健康需求人群",
    "pain_points": "藥品市場推廣受限流，想知道如何推進。; 保健品市場 entry strategy 如何策劃。; 有限資源下，不同類型產品應投放哪些電商平台。; 保健品領域中，對比其他海外及本地市場產品，如何發展自身優勢。; 內地政府對保健品政策難以掌握。; 推廣限制不清楚。; 全新品牌 / 全新產品應以什麼策略進入內地市場。; 有限資金下，應先重點投資哪一個平台。; 如何知道市場 trend。",
    "needs": "刺激銷售。; 增加有利潤的銷售渠道。; 在某一個產品領域成為龍頭。; 分享其他保健品策略。; 分享市場及政策要注意的地方。; 分享電商平台推廣建議。; 希望提供藥品及保健品領域經驗作參考，有效指導 entry market strategy。",
    "service_segment": "B1 合規重類目入場",
    "recommended_services": "OPM/平台代運營診斷；合規/跨境入場路線；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Compliance-Led Market Entry",
    "email_subject": "跟進香港好物節諮詢：合規類目入場與內容邊界",
    "personalization_hook": "您的品類涉及保健、酒類、食品或個護宣稱，入場前需要同時處理平台、內容和合規邊界。",
    "cta_next_action": "先確認產品備案/進口方式/宣稱限制，再建議平台和內容節奏。",
    "missing_data": "具體保健品成分、備案狀態、毛利、預算、預計上架時間。",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC_11家公司總結_及_問卷已填資料全集.md",
    "source_confidence": "High",
    "consulting_expectations": "",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2026-006",
    "program_year": 2026,
    "company": "Natural Health Care Development Limited",
    "chinese_name": "",
    "industry_group": "食品飲品",
    "product_category": "中成藥及保健食品",
    "brand": "仙然康寶",
    "contact": "Vivian Lam",
    "title": "市場經理",
    "email": "vivian@naturalhk.com",
    "phone": "3118 7638",
    "website": "https: / www.naturalhk.com",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "京東/京東國際: 已勾選",
    "start_time": "今年剛打算開始內地電商業務",
    "target_customer": "30-60 歲人士",
    "pain_points": "平台運營成本高。; 運營團隊建設困難。; 對剛開始做電商業務的公司來說起步難。; 品牌知名度不高時，很難有好的銷售量。",
    "needs": "增加知名度。; 增加銷售渠道。; 對品牌定位、銷售渠道建設及電商平台種草有更多系統性規劃。; 以合理預算增加品牌知名度及銷售量。; 特別希望打造出爆品。",
    "service_segment": "B1 合規重類目入場",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；合規/跨境入場路線；品牌定位與信任建立；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Compliance-Led Market Entry",
    "email_subject": "跟進香港好物節諮詢：合規類目入場與內容邊界",
    "personalization_hook": "您的品類涉及保健、酒類、食品或個護宣稱，入場前需要同時處理平台、內容和合規邊界。",
    "cta_next_action": "先確認產品備案/進口方式/宣稱限制，再建議平台和內容節奏。",
    "missing_data": "公司規模、成立時間、預算、合規 / 備案狀態、主推 SKU 的銷售數據。",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC_11家公司總結_及_問卷已填資料全集.md",
    "source_confidence": "High",
    "consulting_expectations": "",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2026-007",
    "program_year": 2026,
    "company": "Orbit Baby Limited",
    "chinese_name": "",
    "industry_group": "母嬰/嬰童",
    "product_category": "大件嬰兒產品，包括嬰兒車、嬰兒汽車座椅、睡籃",
    "brand": "Orbit Baby",
    "contact": "Gary Chan",
    "title": "Business Development Manager",
    "email": "gary@orbitbaby.co.kr",
    "phone": "6026 1850",
    "website": "Orbitbabycn.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "抖音: Orbitbaby；淘寶/天貓: Orbit Baby 旗艦店；京東/京東國際: Orbit Baby 母嬰旗艦店；小紅書商城: Orbit Baby；微信: OrbitBaby",
    "start_time": "2025 年 3 月正式開始在內地電商銷售",
    "target_customer": "高端初生嬰兒的父母",
    "pain_points": "剛進內地市場，客人對品牌信心不足。; 品牌針對高端市場，需要更有效宣傳。; 內地市場太大，電商流量成本貴。; 投入及產出比例不成正比。; 不知道如何有效運用 marketing 預算。; 內地電商需要大量曝光，曝光需要內容。; 圖文或視頻內容拍攝成本非常高。; 不確定應專注一個平台還是分散投資。; 天貓大節宣傳分派流量不足，直接影響銷量。",
    "needs": "首要是增加銷售，至少希望今年可收支平衡。; 增加流量成本成效。; 直接增加品牌知名度。; 增加線下合作，使客人增加對品牌的信心。; 利用更多 AI 幫助製作內容、降低成本。; 以專業角度回顧過去一年運作是否有效或不足。; 參考同行成功例子，判斷能否應用到自己公司。; 解決現時運作上遇到的困難。; 有機會對接國內線下分銷商。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "各平台銷售、流量、轉化、投放、退貨、內容成本及線下合作現況。",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC_11家公司總結_及_問卷已填資料全集.md",
    "source_confidence": "High",
    "consulting_expectations": "",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2026-008",
    "program_year": 2026,
    "company": "Tranquillity Acoustronics (HK) Limited",
    "chinese_name": "",
    "industry_group": "家居/家電科技",
    "product_category": "吹風機",
    "brand": "凌波細語",
    "contact": "楊志宇",
    "title": "CEO",
    "email": "phyang@ust.hk",
    "phone": "852 9472 5814",
    "website": "https: / www.acoustronics.com.hk/en",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "抖音: 凌波怡声；淘寶/天貓: 凌波怡声；小紅書商城: 凌波怡声；微信: 凌波怡声",
    "start_time": "2024 公司亦表示目前仍在籌備中，尚未正式起步。",
    "target_customer": "",
    "pain_points": "籌備中，還未正式起步。; 最大挑戰是公司聲音 / 流量被大品牌流量淹沒。; 真相被掩埋，技術優勢難以被市場看見。",
    "needs": "為產品創立以領先全球科技為核心價值的香港品牌。; 提供適合產品特質的內容營銷策略。; 提供情緒共鳴營銷策略。; 提供路線圖。; 提供大致時間表。; 提供成本開支建議。",
    "service_segment": "B2 內容種草/社媒增長",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 4,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Content and KOL Launch Plan",
    "email_subject": "跟進香港好物節諮詢：內容種草與KOL/KOC試水方案",
    "personalization_hook": "您的核心問題適合用內容場景、測評和KOL/KOC小步試水來降低冷啟動風險。",
    "cta_next_action": "安排20分鐘確認內容素材、目標人群和試水預算，我們可給第一輪內容選題。",
    "missing_data": "目標客群；量產 / 庫存狀態、毛利、銷售數據、測試報告可否公開、預算。",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC_11家公司總結_及_問卷已填資料全集.md",
    "source_confidence": "High",
    "consulting_expectations": "",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2026-009",
    "program_year": 2026,
    "company": "AJC Investment Ltd",
    "chinese_name": "",
    "industry_group": "其他消費品",
    "product_category": "",
    "brand": "",
    "contact": "Joanna Mak",
    "title": "",
    "email": "cs@neoyouth.com.hk",
    "phone": "",
    "website": "www.neoyouth.com.hk",
    "platform_stage": "資料不足/待確認",
    "mainland_platforms": "",
    "start_time": "",
    "target_customer": "",
    "pain_points": "掃描內容可辨識度不足。; 可見大意：希望了解入駐內地電商 / 好物節渠道及後續安排。",
    "needs": "了解品牌入駐內地的簡便渠道。; 了解後續跨境合作。; 了解網店 / 虛擬諮詢。; 提升知名度。",
    "service_segment": "C1 先補KYC資料",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立",
    "data_completeness": "Low",
    "data_score": 1,
    "stage_score": 2,
    "fit_score": 2,
    "urgency_score": 3,
    "outreach_status": "KYC Required",
    "campaign": "KYC First Qualification",
    "email_subject": "跟進香港好物節諮詢：先補齊產品與渠道資料",
    "personalization_hook": "目前資料不足，先補齊產品、渠道、合規和預算後，策略會更準確。",
    "cta_next_action": "回覆主推SKU、價格、目標客群、現有渠道和90日預算即可開始分流。",
    "missing_data": "主推SKU/品牌/產品類別；目標客群；公司規模、成立時間、產品類別、主推 SKU、品牌、價格、目標客群、現有渠道、銷售情況、具體痛點。; 會議第一步應先補 KYC。；價格/毛利/庫存；現有渠道與銷售數據；90日測試預算",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC_11家公司總結_及_問卷已填資料全集.md",
    "source_confidence": "Medium",
    "consulting_expectations": "",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2026-010",
    "program_year": 2026,
    "company": "Magic Of Scents International Ltd",
    "chinese_name": "",
    "industry_group": "美容/個人護理",
    "product_category": "未見填寫，但附件顯示為防曬 / 個人護理",
    "brand": "Epinix",
    "contact": "Celia",
    "title": "CFO",
    "email": "Celia@plluk.com",
    "phone": "2110 9948",
    "website": "",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "京東/京東國際: 問卷中有勾選",
    "start_time": "Not yet / 尚未開始",
    "target_customer": "未見填寫",
    "pain_points": "問卷未見具體填寫。; 從資料判斷主要缺口為：尚未開始內地電商，需要釐清平台、定位、合規和推廣方式。",
    "needs": "問卷未見具體填寫。; 需會上補問：; 想先做品牌曝光還是銷售？; 防曬產品是否已完成內地 / 跨境合規？; 目標客群是女士、敏感肌、戶外、男士、妝前還是日常通勤？",
    "service_segment": "C1 先補KYC資料",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；合規/跨境入場路線；品牌定位與信任建立",
    "data_completeness": "Low",
    "data_score": 1,
    "stage_score": 4,
    "fit_score": 2,
    "urgency_score": 5,
    "outreach_status": "KYC Required",
    "campaign": "KYC First Qualification",
    "email_subject": "跟進香港好物節諮詢：先補齊產品與渠道資料",
    "personalization_hook": "目前資料不足，先補齊產品、渠道、合規和預算後，策略會更準確。",
    "cta_next_action": "回覆主推SKU、價格、目標客群、現有渠道和90日預算即可開始分流。",
    "missing_data": "目標客群、價格、銷售現況、平台計劃、主要挑戰、具體期望、合規狀態。；價格/毛利/庫存；現有渠道與銷售數據；90日測試預算",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC_11家公司總結_及_問卷已填資料全集.md",
    "source_confidence": "Medium",
    "consulting_expectations": "",
    "story_selling_points": "See attachment，問卷內未見詳細文字"
  },
  {
    "lead_id": "TDC2026-011",
    "program_year": 2026,
    "company": "Premier Living (Enterprises) Co Ltd",
    "chinese_name": "",
    "industry_group": "美容/個人護理",
    "product_category": "Skincare",
    "brand": "B'LIFEY",
    "contact": "Richard Chu",
    "title": "Executive Director",
    "email": "RCHU@PLIVINGMALL.COM",
    "phone": "2815 0626 / 9023 6326",
    "website": "www.beautyonlinehk.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "香港設計廊(京東國際)",
    "start_time": "2026 年 2 月 1 日 / FEB. 01, 2026",
    "target_customer": "18 years old or above",
    "pain_points": "市場大，但競爭也大，很難產生銷售。; 沒有投放廣告的資源。; 沒有銷售。",
    "needs": "產生銷售。; 增加知名度。; 了解更多怎樣發展國內市場。; 了解如何計算開發國內市場所需資本。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "主推 SKU、產品成分 / 功效、毛利、樣品數量、預算上限、內容資產。",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC_11家公司總結_及_問卷已填資料全集.md",
    "source_confidence": "High",
    "consulting_expectations": "",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2025-001",
    "program_year": 2025,
    "company": "AAA Noodle Product Manufactory (HK) Ltd.",
    "chinese_name": "中國(香港)製麵廠有限公司",
    "industry_group": "食品飲品",
    "product_category": "糧油調味>挂麵>傳統挂麵",
    "brand": "錦華坊",
    "contact": "Stanley Chow | 周曉青",
    "title": "Manager",
    "email": "stanley@gourmetalley.com.hk",
    "phone": "2614 2160 | 6278 1633",
    "website": "gourmetalley.com.hk",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "申請中: 香港設計廊 (京東國際)",
    "start_time": "籌備中",
    "target_customer": "健康養生, 銀髮族",
    "pain_points": "如何選擇適合的平台 如何建立電商網店 如何營運網店",
    "needs": "增加銷售渠道 增加知名度 / 增加知名度 刺激銷售 / 刺激銷售",
    "service_segment": "A2 從零入場/開店搭建",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 4,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "90-Day Market Entry Sprint",
    "email_subject": "跟進香港好物節諮詢：90日內地電商入場方案",
    "personalization_hook": "您目前處於準備或剛入場階段，重點是先選對主推SKU、平台和最低可行測試預算。",
    "cta_next_action": "安排20分鐘確認主推SKU、入場方式和預算，我們可整理一版90日路線圖。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__AAA Noodle Product Manufactory (HK) Ltd (no mainland online shop) 20250326.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "如何選擇適合的平台 如何建立電商網店 如何營運網店",
    "story_selling_points": "香港錦華坊是一家近四十年歷史、最具規模的港式傳統優質乾麵生產商和出口商, 一直堅持正宗傳統、一絲不苟的非油炸自然製麵工藝 , 傳承逾半世紀製麵老師傅們的技術秘笈, 嚴選優質進口小麥麵粉等天然食材 , 食物安全鑑定出品，為顧客提供美味又安心食用的優質港式傳統麵食 ，其卓越的品質和經典的風味深受香港和海外顧客的讚許。"
  },
  {
    "lead_id": "TDC2025-002",
    "program_year": 2025,
    "company": "Faithco International Limited",
    "chinese_name": "飛浩國際有限公司",
    "industry_group": "食品飲品",
    "product_category": "有機茶包",
    "brand": "“飛浩” 南非天然有機純茶",
    "contact": "Sabrina Tang | 鄧雪珍",
    "title": "Manager",
    "email": "sabrina@faithco.com.hk",
    "phone": "2895 5580 | 9086 8733",
    "website": "www.faithco.com.hk",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "其他: 順豐內部職員平台 - 2024/7",
    "start_time": "2024/05",
    "target_customer": "喜歡追求健康人士",
    "pain_points": "本公司資源小，對電商市場不認識，運作上有困難",
    "needs": "打開內地市場，刺激銷售、增加知名度、增加銷售渠道等",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__Faithco International Limited 20250328.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "可以協助運作電商平台，能開展公司產品業務",
    "story_selling_points": "選用南非獨有100%頂級的針松狀紅灌木烘製茶包，又名南非國寶茶。2015年美國TIME時代雜誌撰文列入50種最健康飲品之一，取得歐盟、南非和美國有機認證。不含咖啡因，適合兒童、成人任何人仕飲品。 助舒緩焦慮壓力，寧神安睡；改善人體血管微循環系統，防心血管疾病和調低血糖值；高抗氧化幫助細胞修復，防皮膚過敏，抵禦自由基侵害，腦細胞精靈、增加好膽固醇、腸道暢通。家庭健康茗閒茶首選之一。"
  },
  {
    "lead_id": "TDC2025-003",
    "program_year": 2025,
    "company": "Fidelity Food and Beverage Group Company Limited",
    "chinese_name": "忠餐飲文化有限公司",
    "industry_group": "食品飲品",
    "product_category": "食品",
    "brand": "香港奀師傅",
    "contact": "June Lui | 呂麗珍",
    "title": "Executive Director",
    "email": "junelui68@hotmail.com",
    "phone": "3619 4527 | 6462 8572",
    "website": "www.hkmasterngan.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "抖音: 香港奀師傅 2024；淘寶/天貓: 香港奀師傅 2024",
    "start_time": "2024年",
    "target_customer": "一線城市30-40歲中高收入群體",
    "pain_points": "核心痛點在於品牌認知門檻高導致流量成本高，香港特色與內地消費場景適配不足，切電商平台 流量規則複雜（如抖音算法迭代快），內容轉化效率難達預期，獲客與留存壓力大。",
    "needs": "首要期望：以電商為入口，打開線下高端渠道銷售 目標：通過天貓旗艦店銷量背書，反向拓展一線城市精品超市、高端社區生鮮便利店，形成線上種 / 目標：通過天貓旗艦店銷量背書，反向拓展一線城市精品超市、高端社區生鮮便利店，形成線上種 草、線下體驗、全域復購閉環，強化品牌高端質感。 / 草、線下體驗、全域復購閉環，強化品牌高端質感。",
    "service_segment": "B1 合規重類目入場",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；合規/跨境入場路線；品牌定位與信任建立；私域/CRM/復購；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Compliance-Led Market Entry",
    "email_subject": "跟進香港好物節諮詢：合規類目入場與內容邊界",
    "personalization_hook": "您的品類涉及保健、酒類、食品或個護宣稱，入場前需要同時處理平台、內容和合規邊界。",
    "cta_next_action": "先確認產品備案/進口方式/宣稱限制，再建議平台和內容節奏。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__Fidelity Food and Beverage Group Company Limited 20250321.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "1、合規優先，期望熟悉跨境法規（法務、數據隱私）及電商平台規則 、全渠道引流策略。 2、數據驅動策略，市場分析、競品對標與流量增長方案。 3、確保具備國際經驗與落地執行力，推動業務增長。",
    "story_selling_points": "奀師傅誕生於香港，秉持著對傳統港式烹飪技藝的尊崇和堅守，致力還原一道道經典港式美食，打破地區限製，把正宗香港風味的「味覺明信片」投遞到世界每一個角落，讓各地的美食愛好者足不出戶，便能開啟一場沈浸式的香港美食之旅。"
  },
  {
    "lead_id": "TDC2025-004",
    "program_year": 2025,
    "company": "G. M. Global (China) Limited",
    "chinese_name": "",
    "industry_group": "酒類",
    "product_category": "蜂蜜葡萄紅/白酒 Godlen Velvet Honey Infused Wine",
    "brand": "Golden Velvet Honey Infused Wine",
    "contact": "Rosa Tsang / 曾敏兒",
    "title": "BD Director",
    "email": "rosa@gmg-china.com",
    "phone": "2114 0035 / 6644 9789",
    "website": "www.goldenvelvet-honeywines.com",
    "platform_stage": "申請中/準備入場",
    "mainland_platforms": "香港設計廊(京東國際)；申請中: 小紅書商城/公眾號/抖音；自家小程序",
    "start_time": "2025 年 4 月",
    "target_customer": "不常喝紅酒,不喜歡紅酒苦澀味的大眾",
    "pain_points": "人口龐大如何找對的客戶，還有是會持續購買",
    "needs": "刺激銷售、增加知名度、增加銷售渠道",
    "service_segment": "B1 合規重類目入場",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；合規/跨境入場路線；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 5,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Compliance-Led Market Entry",
    "email_subject": "跟進香港好物節諮詢：合規類目入場與內容邊界",
    "personalization_hook": "您的品類涉及保健、酒類、食品或個護宣稱，入場前需要同時處理平台、內容和合規邊界。",
    "cta_next_action": "先確認產品備案/進口方式/宣稱限制，再建議平台和內容節奏。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__G. M. Global (China) Limited 20250326.pdf.txt",
    "source_confidence": "High",
    "consulting_expectations": "可以指導出我們如何在自媒體擴展生意",
    "story_selling_points": "G.M. Global 成立于 2013 年，主营与南非进出口业务，特別是葡萄酒。 于 2017 年在南非自设酒庄研发蜂蜜红酒，研发近三年，调制出独特配方 和技术，令南非皇帝花蜂蜜 100%融入葡萄酒里， 完美平衡葡萄酒丹宁的 酸涩感觉，非常适合配搭中西或东南亚菜系。现全球寻找合作伙伴或总经 销商。 獲得 2023 年 SIAL 食品創新大獎"
  },
  {
    "lead_id": "TDC2025-005",
    "program_year": 2025,
    "company": "In-Well Ltd",
    "chinese_name": "御殿堂有限公司",
    "industry_group": "食品飲品",
    "product_category": "食品及飲品",
    "brand": "IKA’s、娘惹料理、巴生后街慶成、開吃吧！等等",
    "contact": "Simon Sy | 施身廸",
    "title": "董事",
    "email": "info@i-w.com.hk",
    "phone": "6892 2322",
    "website": "www.memarket.hk",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "",
    "start_time": "2025年",
    "target_customer": "中高消費級客群",
    "pain_points": "物流成本過高，食品入口中國規範",
    "needs": "刺激銷售、增加銷售渠道",
    "service_segment": "B1 合規重類目入場",
    "recommended_services": "OPM/平台代運營診斷；合規/跨境入場路線；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Compliance-Led Market Entry",
    "email_subject": "跟進香港好物節諮詢：合規類目入場與內容邊界",
    "personalization_hook": "您的品類涉及保健、酒類、食品或個護宣稱，入場前需要同時處理平台、內容和合規邊界。",
    "cta_next_action": "先確認產品備案/進口方式/宣稱限制，再建議平台和內容節奏。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__In-Well Ltd (no mainland online shop) 20250328.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "了解更多電商道及加快上架流程",
    "story_selling_points": "MEmarket特急殿堂（御殿堂有限公司）是專業級馬來西亞食品店和批發供應商，以馬來西亞食品店起家，發展至今已是十多個品牌的獨家代理商。我們的食材店從一而終地為客人帶來地道口味，用心揀選肉骨茶湯包、白咖啡、娘惹料理醬料及花生糖等美食，久而久之累積了多款人氣食品，推崇絕佳的食品體驗。"
  },
  {
    "lead_id": "TDC2025-006",
    "program_year": 2025,
    "company": "JLE (China) Limited",
    "chinese_name": "",
    "industry_group": "醫藥/保健品",
    "product_category": "母婴辅食",
    "brand": "Ella’s Kitchen 艾拉厨房",
    "contact": "Hui Yang | 楊慧",
    "title": "Brand Manager",
    "email": "yubelyang@ecgservice.com",
    "phone": "(86) 1391 861 4260",
    "website": "ecgservice.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "抖音: 艾拉厨房海外旗舰店 2025年；淘寶/天貓: ellaskitchen海外旗舰店 2016年",
    "start_time": "我司一直深耕跨境贸易，最早从2015年就开始做电子商务了。",
    "target_customer": "0-1 岁的婴儿、1-3 岁的幼儿、家长、关注宝宝健康的人群、注重便捷性的消费者、经常出行的家庭",
    "pain_points": "渠道与流量方面：平台流量红利见顶或市场格局发生变化时，公司业务容易受到冲击。 流量成本上升：电商市场进入存量竞争，各平台流量变得稀缺，获取流量成本不断增加。 品牌知名度方面：更多品牌缺少品牌营销，需要更多的人力时间与资金成本来获取更多的流量。",
    "needs": "营销推广方面：品牌策略福利，品牌本身影响力，赠品的支持玩法来提升销售。 品牌建设方面：根据中国市场的文化特点消费者的审美观念，对品牌形象进行本地化设计和优化。 / 品牌建设方面：根据中国市场的文化特点消费者的审美观念，对品牌形象进行本地化设计和优化。 销售渠道拓展方面：除了天猫旗舰店本身，探索与其他电商平台或线下渠道的合作机会，实现线上线下渠道的融合。 / 销售渠道拓展方面：除了天猫旗舰店本身，探索与其他电商平台或线下渠道的合作机会，实现线上线下渠道的融合。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__JLE (China) Limited 20250402.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "增加品牌的曝光知名度，期待有更多的达人KOL能够带动品牌的声量和产品销售。",
    "story_selling_points": "英国皇室同款辅食，连续9年英国销量冠军，100% 有机认证，精选优质有机水果和蔬菜，无农药残留无添加剂，欧盟有机认证、美国USDA有机认证，从源头就和农药残留、添加剂说拜拜，每一口都是大自然纯粹的味道。妈妈必备，3秒开盖，营养满分的快手辅食，宝宝爱吃妈妈省心。4个月龄的宝宝就可以吃哦！"
  },
  {
    "lead_id": "TDC2025-007",
    "program_year": 2025,
    "company": "Kadosh Health & Beauty Company Limited",
    "chinese_name": "卡道斯有限公司",
    "industry_group": "食品飲品",
    "product_category": "保健產品",
    "brand": "「卡道斯」-Kadosh",
    "contact": "Yuen Ming Pang | 彭婉明",
    "title": "CEO",
    "email": "mingpang@kadosh-health.com",
    "phone": "3422 3815 | 6053 0005",
    "website": "www.kadosh.hk",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "",
    "start_time": "公司打算2025年8月開始內地電商業務",
    "target_customer": "綜合品牌都是以大學科研為依據，所以目標客戶群是中產及以上，不太是盲目相信明星效應、較為知識型人群。 | 一、睡眠类产品核心客群（男、女，年齡30至99歲） | 睡眠質素欠佳人士 | 多夢易醒或入睡困難人士 | 失眠人士 | 長期服食安眠藥物人士 | 希望提升睡眠質素人士 | 忙碌導致睡眠時間短人士 | 二、护眼类产品核心客群（男女老幼，五歲至99歲人士皆宜服用） | 長者及眼退化人群 | 學生、辦公室人群 | 經常用手機, 電腦人群 | 電競職業人群 | 三、男士健康类产品核心客群 | 男士， 25歲以上关注男士機能、補腎、持久力提升人群 | 也需要顧問建議以上三隻產品，先由（1）那一隻產品開始重點做國內市場，及（2）目標人群（3）價格。",
    "pain_points": "1. 第一痛點是沒有人才, 抖音等興趣電商需掌握短視頻內容行銷和直播帶貨玩法，與香港傳統零售模式差異大，缺乏专业人才。 2. 第二痛點是投放及資金好大，作為中小企要跟大品牌，維特健靈、樂道等競爭，他們全部都用明星 、好多錢及人手投入中國市場。 3.公司还未開始內地電商巿場，该以什么渠道进入內地電商巿場？ 4. 跨境物流時效難保障：直郵模式用戶體驗差，保稅倉備貨需預支高額倉儲費用。 5.內地對進口保健食品實施嚴格的「藍帽子」註冊制度，該如何用食品渠道進入？",
    "needs": "刺激銷售但要有錢賺，打開國內市場。因為我們作為中小企，不像大公司，資金很充足， 可以蝕幾年錢為了打響知名度。我們進入中國市場，首要目的希望是平衡銷售和要賺錢。 / 可以蝕幾年錢為了打響知名度。我們進入中國市場，首要目的希望是平衡銷售和要賺錢。",
    "service_segment": "B1 合規重類目入場",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；合規/跨境入場路線；品牌定位與信任建立；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Compliance-Led Market Entry",
    "email_subject": "跟進香港好物節諮詢：合規類目入場與內容邊界",
    "personalization_hook": "您的品類涉及保健、酒類、食品或個護宣稱，入場前需要同時處理平台、內容和合規邊界。",
    "cta_next_action": "先確認產品備案/進口方式/宣稱限制，再建議平台和內容節奏。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__Kadosh Health Beauty Company Limited (no mainland online shop) 20250326.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "用最低成本，達到首要期望。因為公司未開始內地電商市場，所以好需要前期專業的指導， 幫助公司少走彎路。如何用最低成本先試試水？",
    "story_selling_points": "品牌故事： | | 品牌名字Kadosh 是希伯來文（意思：與眾不同），中文翻譯「卡道斯」，是指公司抱著不一樣的使命。 | | 公司使命是宣揚： | 1）「中醫中藥- 治末病」概念 | 2）把「中藥現代化」 | 3）推動「 香港本地大學科硏、及香港製造」 | | 因此公司與 | 1） 香港科技大學 | 2）及「香港中文大學-中醫學院」 | 3）及香港中文大學-全資附屬中藥研究所「香港生物科技研究院」 | | 共同科研合作，硏製出一系列：高效、優質、安全，純天然草本保健品。希望令市民更加健康。 | | 產品特點: 高效、安全 | | 公司是全香港，「唯一品牌」全線產品，都是與上述2 間大學機構，「一條龍大學科研及製造」。 | 以確保產品功效及安全性。 | 並且「每一批」產品都通過國際認證機構SGS , 逾30多項安全性測試，才推出市面。"
  },
  {
    "lead_id": "TDC2025-008",
    "program_year": 2025,
    "company": "Kamcha Company Limited",
    "chinese_name": "金茶王有限公司",
    "industry_group": "食品飲品",
    "product_category": "港式樽裝飲品系列/茶/奶制品/奶茶设备等",
    "brand": "金茶王",
    "contact": "Yiu Yu Li / 李曜余",
    "title": "Marketing Executive",
    "email": "isalinali@kamcha.com.hk",
    "phone": "3181 4433 / 5400 0654",
    "website": "www.kamcha.com.hk",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "抖音: 金茶王 (2022)；淘寶/天貓: 金茶王品牌直营店 (2016)",
    "start_time": "2016 年",
    "target_customer": "以 B 端餐饮服务为核心，產品覆盖連鎖超市到連鎖高铺，同时通过零 售渠道触达 C 端消费者，并依托品牌文化影响力拓展海外市场。",
    "pain_points": "电商平台运营：不同电商平台的运营规则和用户群体差异较大，需要投入更多精力进行精细化运 营，提升用户体验和转化率  品牌认知度：虽然金茶王在香港及海外市场有一定知名度，但在内地市场，品牌认知度仍有待提 升，尤其是在竞争激烈的饮品市场中，需要进一步强化品牌影响力。  消费者教育：港式奶茶等产品在内地部分地区的消费者认知度较低，需要投入更多资源进行消费者 教育，介绍产品特色和文化背景，以吸引消费者尝试和购买。",
    "needs": " 首要期望：增加知名度。通过电商平台扩大品牌影响力，提升品牌在内地市场的知名度和美誉度， 吸引更多消费者关注和购买金茶王的产品。  刺激销售：通过拓展内地电商业务，进一步提升销售额，实现业务增长，特别是在内地市场的重点 城市和地区，实现销售的快速增长。  增加销售渠道：利用电商平台的便捷性和广泛性，增加销售渠道，触达更多潜在消费者，进一步扩 大市场覆盖范围。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；合規/跨境入場路線；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__Kamcha Company Limited 20250327.pdf.txt",
    "source_confidence": "High",
    "consulting_expectations": " 深入了解内地电商市场趋势：希望本次咨询服务能够提供内地电商市场的最新趋势和动态，帮助我 们更好地制定业务策略，把握市场机会。 PAGE 2 / 2 [PDF PAGE 2 TABLE 1] 电商平台运营 / ：不同电商平台的运营规则和用户群体差异较大，需要投入更多精力进行精细化运 [PDF PAGE 2 TABLE 2] 品牌认知度：虽然金茶王在香港及海外市场有一定知名度，但在内地市场，品牌认知度仍有待提 升，尤其是在竞争激烈的饮品市场中，需要进一步强化品牌影响力。 消费者教育：港式奶茶等产品在内地部分地区的消费者认知度较低，需要投入更多资源进行消费者 教育，介绍产品特色和文化背景，以吸引消费者尝试和购买。 [PDF PAGE 2 TABLE 3] 首要期望：增加知名度。通过电商平台扩大品牌影响力，提升品牌在内地市场的知名度和美誉度， 吸引更多消费者关注和购买金茶王的产品。 刺激销售：通过拓展内地电商业务，进一步提升销售额，实现业务增长，特别是在内地市场的重点 城市和地区，实现销售的快速增长。 增加销售渠道：利用电商平台的便捷性和广泛性，增加销售渠道，触达更多潜在消费者，进一步扩 大市场覆盖范围。 [PDF PAGE 2 TABLE 4] 深入了解内地电商市场趋势：希望本次咨询服务能够提供内地电商市场的最新趋势和动态，帮助我 们更好地制定业务策略，把握市场机会。 [PDF PAGE 3]  获取专业建议：针对我们在内地电商业务中面临的问题和挑战，提供专业的解决方案和建议，帮助 我们优化业务流程，提升运营效率，特别是在品牌推广、消费者教育和物流配送等方面。  建立合作机会：通过本次咨询服务，寻找潜在的合作机会，拓展业务领域和合作伙伴，共同推动电 商业务的发展，例如与电商平台、物流合作伙伴等建立更紧密的合作关系。",
    "story_selling_points": "2009 年金茶王有限公司誕生; 開始舉辦第一屆香港金茶王大賽。其 後亦有在歷屆工展會舞台上舉辦金茶王大賽， 和參加香港貿易發展局 的香港國際茶展。金茶王產品在剛起步的時候只有簡約的概念和設 計，希望充分了解市場需求後，才將金茶王產品推出。2010 年開始舉 辦國際金茶王大賽。現今，國際金茶王賽區包括：香港, 國內主要城市, 北美, 澳洲等地。2014 年黃家和太平紳士將港式奶茶製作技藝成功申請 成為「香港非物質文化遺產」。2017 年港式奶茶製作技藝成為「香港 非物質文化遺產」二十大代表作之一。"
  },
  {
    "lead_id": "TDC2025-009",
    "program_year": 2025,
    "company": "Maxcare Industrial Limited",
    "chinese_name": "美斯凱實業有限公司",
    "industry_group": "家居/家電科技",
    "product_category": "按摩椅, 按摩器",
    "brand": "Maxcare",
    "contact": "Rachel Leung | 梁美玲",
    "title": "Assistant Marketing Manager",
    "email": "rachelleung@maxcare.com.hk",
    "phone": "2172 7318 | 6311 8216",
    "website": "www.maxcareonlineshop.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "抖音: Maxcare美斯凯按摩器旗舰店 2023；淘寶/天貓: Maxcare美斯凯旗舰店 2019；京東/京東國際: Maxcare美斯凯旗舰店 2019；小紅書商城: Maxcare美斯凯 2023；微信: Maxcare美斯凯按摩椅 2019；微博: Maxcare美斯凯 2018",
    "start_time": "2019年開始",
    "target_customer": "年齡: 25 – 65+",
    "pain_points": "內地電商市場競爭激烈，天貓和京東等平台面臨來自拼多多等產業帶品牌（白牌）的低端衝擊，逐步引導低價產品的轉化數據越來越好；相對而言，我司的轉化率下降，主要是因為用戶標籤匹配度不足，以及投入產出不成比例。產品的核心算法中，轉化率是重點指標，導致店鋪逐漸降低熱度。 | | 此外，在內地建立品牌知名度需要時間和大量資源，更需要相應的知識去策劃有效的市場營銷和推廣活動以促進品牌知名度。面對內地市場消費降級的趨勢，以飛利浦和奧克斯為首的國內個人護理品牌大肆充斥線上市場，依靠品牌知名度和低價策略，通過直播快速轉化客戶群。在產品體驗不足的情況下，我司被迅速佔領市場，未能贏得口碑和品牌認知。 | | 另一方面，內地消費者的需求和偏好與香港市場差異較大，其中一個挑戰是需要投入資源進行市場調查和研究，以了解目標消費者的行為和需求。",
    "needs": "期望提升品牌知名度，透過有效的市場營銷策略刺激銷售，從而擴大品牌的市場發展，以達到更高的銷售額和利潤。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__Maxcare Industrial Limited 20250327.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "期望獲得內地電商市場的專業分析和建議，包括了解消費者行為、競爭對手分析和行業動態等，了解更多有效的營銷策略。希望透過諮詢過程能提供具體的實施步驟和指導，並能提供量身定制的營銷策略，以符合我司的具體需求和目標，改善現況。",
    "story_selling_points": "品牌故事：Maxcare集團領導人憑著二十多年生產健康按摩產品經驗，了解亞洲人對按摩產品的特別需求，創立了Maxcare品牌，並於2012年在香港大力拓展按摩產品市場，更於2017年獲得香港名牌殊榮。 Maxcare以香港作為基地，專注於研發、生產及銷售家庭健康器械。 | | 產品賣點：不斷推出創新性的按摩產品，以大眾化的價格定位提供高品質，並擁有完善的售後和保修服務。"
  },
  {
    "lead_id": "TDC2025-010",
    "program_year": 2025,
    "company": "Merge Enterprise Ltd",
    "chinese_name": "浚一企業有限公司",
    "industry_group": "食品飲品",
    "product_category": "米",
    "brand": "東香醉",
    "contact": "Shervon Chan | 陳楊健玉",
    "title": "Chief Marketing Officer",
    "email": "shervon@merge.com.hk",
    "phone": "3576 3840 | 9123 5407",
    "website": "merge.hk",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "",
    "start_time": "２０２２",
    "target_customer": "",
    "pain_points": "我們在內地電商市場面臨的最大挑戰是激烈的競爭和價格敏感性。內地電商市場競爭非常激烈， 大量本地及國際米類品牌。許多競爭對手以低價策略吸引消費者，這對我們的高端米類產品 造成壓力。內地消費者往往更注重價格而非品質，這使得我們的高質高價定位難以快速打入市場。",
    "needs": "我們對發展內地電商業務的首要期望是在內地消費者中建立強大的品牌知名度和信任感 將東香醉打造成優質、健康米類產品的首選品牌。我們希望利用內地市場對營養和正宗食品日益 / 將東香醉打造成優質、健康米類產品的首選品牌。我們希望利用內地市場對營養和正宗食品日益 增長的需求，通過針對性的營銷活動，突出我們的獨特賣點以及產品的健康益處 / 增長的需求，通過針對性的營銷活動，突出我們的獨特賣點以及產品的健康益處 從而與低價競爭對手區分開來。我們的目標是培養一批重視品質、願意為優質米類產品支付溢價的 / 從而與低價競爭對手區分開來。我們的目標是培養一批重視品質、願意為優質米類產品支付溢價的 忠實客戶群。 / 忠實客戶群。",
    "service_segment": "A2 從零入場/開店搭建",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 4,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "90-Day Market Entry Sprint",
    "email_subject": "跟進香港好物節諮詢：90日內地電商入場方案",
    "personalization_hook": "您目前處於準備或剛入場階段，重點是先選對主推SKU、平台和最低可行測試預算。",
    "cta_next_action": "安排20分鐘確認主推SKU、入場方式和預算，我們可整理一版90日路線圖。",
    "missing_data": "目標客群",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__Merge Enterprise Ltd 20250327.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "我們期望通過香港好物節2025的一對一專業顧問諮詢服務，獲得可行性策略和深入見解 ，獲得可行性策略和深入見解，以克服我們在內地電商市場的挑戰。 我們希望專家能提供建議幫助我們在價格敏感的市場中有效定位高端米類產品，優化電商運營 並制定針對內地消費者的數碼營銷策略。 我們期待了解內地電商市場的最新趨勢和消費者偏好，以便調整我們的策略，實現可持續增長。",
    "story_selling_points": "目標客群："
  },
  {
    "lead_id": "TDC2025-011",
    "program_year": 2025,
    "company": "Merlyn Healthcare Limited",
    "chinese_name": "美意年健康科技有限公司",
    "industry_group": "食品飲品",
    "product_category": "營養食物油",
    "brand": "Vita Herbs 真原醫",
    "contact": "Tony Chu / 朱鼎良",
    "title": "Director",
    "email": "tonychu0919@gmail.com",
    "phone": "6300 9272",
    "website": "www.merlynhealth.com",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "香港設計廊(京東國際)；小紅書商城: 港油大叔",
    "start_time": "準備中",
    "target_customer": "高端消費者",
    "pain_points": "産品傳播，直播帶貨平台架建，中港物流。",
    "needs": "借香港直播帶貨成功，建立内地直播帶貨通路。",
    "service_segment": "B2 內容種草/社媒增長",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；合規/跨境入場路線",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 4,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Content and KOL Launch Plan",
    "email_subject": "跟進香港好物節諮詢：內容種草與KOL/KOC試水方案",
    "personalization_hook": "您的核心問題適合用內容場景、測評和KOL/KOC小步試水來降低冷啟動風險。",
    "cta_next_action": "安排20分鐘確認內容素材、目標人群和試水預算，我們可給第一輪內容選題。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__Merlyn Healthcare Limited 20250327.pdf.txt",
    "source_confidence": "High",
    "consulting_expectations": "了解直播帶貨建設，中港物流、保稅倉運作。",
    "story_selling_points": "故事：真原創新食品，良新好油， 香港製造， 英國專利，多國獎項， 香港直播帶貨，最受歡迎品牌。 賣點：藥食同源的 8 種多元化、針對性配方， 其功效世界高度認可、易 理解，效果顯著。"
  },
  {
    "lead_id": "TDC2025-012",
    "program_year": 2025,
    "company": "Pinewood Wine Limited",
    "chinese_name": "楠森洋酒有限公司",
    "industry_group": "酒類",
    "product_category": "紅白酒",
    "brand": "Grand Reyne",
    "contact": "Edward Lau | 劉昭灝",
    "title": "Managing Director",
    "email": "edward.lau@pinewoodwine.com",
    "phone": "2873 0098",
    "website": "pinewoodwine.com",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "",
    "start_time": "2024",
    "target_customer": "喜愛紅酒人仕",
    "pain_points": "關口稅務和公司户口：內地的進口酒類市場有許多規範和要求，包括稅收、檢疫和標籤規定 競爭激烈：電商平台的興起，許多本地和國際品牌都在爭奪市場份額，競爭加劇。 物流和配送：內地電商要求高效的物流和配送系統，尤其是對於易碎品如紅酒，運營成本增加 品牌認知：在競爭激烈的市場中，如何建立品牌信任度和忠誠度是一大挑戰",
    "needs": "增加銷售渠道 — 增加品牌知名度 期待與電商平台建立更緊密的合作關係，開展營銷活動，提升品牌曝光度和銷售額。 / 期待與電商平台建立更緊密的合作關係，開展營銷活動，提升品牌曝光度和銷售額。",
    "service_segment": "B1 合規重類目入場",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；合規/跨境入場路線；品牌定位與信任建立；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Compliance-Led Market Entry",
    "email_subject": "跟進香港好物節諮詢：合規類目入場與內容邊界",
    "personalization_hook": "您的品類涉及保健、酒類、食品或個護宣稱，入場前需要同時處理平台、內容和合規邊界。",
    "cta_next_action": "先確認產品備案/進口方式/宣稱限制，再建議平台和內容節奏。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__Pinewood Wine Limited 20250326.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "期望更了解如何進入內地市場，了解未來發展趨勢。",
    "story_selling_points": "香港OEM品牌"
  },
  {
    "lead_id": "TDC2025-013",
    "program_year": 2025,
    "company": "Profit Royal Pharmaceutical Limited",
    "chinese_name": "盈宗製藥有限公司",
    "industry_group": "食品飲品",
    "product_category": "纸尿裤",
    "brand": "NASK 纳司",
    "contact": "Mandy Leong / 梁敏誼",
    "title": "Sales Admin Officer",
    "email": "mandy.leong@nask.hk",
    "phone": "3900 6200",
    "website": "www.nask.hk",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "香港設計廊(京東國際): 香港設計廊 (2023)；淘寶/天貓: NASK纳司海外旗舰店 (2024)；小紅書商城: NASK纳司海外旗舰店 (2024)；微信: NASK纳司 (2024)",
    "start_time": "2024",
    "target_customer": "患尿布疹的嬰兒",
    "pain_points": "競爭激烈：市場上競爭對手眾多，尤其是知名品牌和本地品牌。 流量成本高：吸引目標受眾的流量成本越來越高，ROI（投資回報率）難以提升。 品牌知名度不足：在內地市場的品牌認知度有限，需要更多資源投入推廣。 平台運營複雜：各大電商平台（如淘寶、京東、拼多多等）規則不同，營運效率有待提升。 消費者信任：建立對品牌的信任需要時間，尤其是針對新進入市場的品牌。",
    "needs": "刺激銷售：希望通過電商進一步提升銷售額，實現快速增長。 增加品牌知名度：進一步提升品牌在內地市場的認知度，進而建立市場地位。 拓展銷售渠道：利用多元化的電商平台（如社交電商等）覆蓋更多消費者群體。 數據洞察：通過電商平台獲取更多消費者行為數據，以便優化產品和營銷策略。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__Profit Royal Pharmaceutical Limited 20250325.pdf.txt",
    "source_confidence": "High",
    "consulting_expectations": "提供深入的市場分析，了解內地電商市場的趨勢與機遇。 制定針對性策略，解決現有痛點，提升電商運營效率。 提供品牌推廣建議，包括如何提升消費者認知和信任。",
    "story_selling_points": "NASK NANO 抗疹殺菌勇士拉拉褲專為尿布疹而設計，有效殺滅 99% 大腸桿菌，保持寶寶嬌嫩的皮膚健康、舒適。憑藉其突破性的納米纖維專 利技術，抗疹殺菌勇士拉拉褲是預防和治療尿布疹的終極解決方案！"
  },
  {
    "lead_id": "TDC2025-014",
    "program_year": 2025,
    "company": "Searange Houseware Limited",
    "chinese_name": "海域家居有限公司",
    "industry_group": "食品飲品",
    "product_category": "玻璃產品（花瓶&酒杯類） 、食品（零食）",
    "brand": "SEARANGE / 多多熊DeDo Bear / Chewy Ginger (代理品牌)",
    "contact": "Janet Chen",
    "title": "Director",
    "email": "janet.chen@searange.com.hk",
    "phone": "9308 8197 /2624 9338",
    "website": "www.searange.com.hk",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "",
    "start_time": "目前还没有做，准备开始做",
    "target_customer": "注重健康生活，有生活品味的人群。",
    "pain_points": "1.我們一直在做傳統的B2B出口生意 ，對B2C的市場不夠瞭解。 2.對於市場上電商的總體情況，如何入手及做好沒有經驗，剛剛開始通過HKTDC設計廊接觸零售客人。 3.對於電商的不同平臺，其客戶群體，具體操作及如何展開銷售等情況不瞭解，不知道應該從哪裡開始。",
    "needs": "剛開始接觸B2C的業務，期望從沒有到有，可以穩定的成長，建立一定的銷售管道，有一群喜歡我 們產品的粉絲，業務能夠慢慢穩步增長。 / 們產品的粉絲，業務能夠慢慢穩步增長。",
    "service_segment": "B1 合規重類目入場",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；合規/跨境入場路線；私域/CRM/復購",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Compliance-Led Market Entry",
    "email_subject": "跟進香港好物節諮詢：合規類目入場與內容邊界",
    "personalization_hook": "您的品類涉及保健、酒類、食品或個護宣稱，入場前需要同時處理平台、內容和合規邊界。",
    "cta_next_action": "先確認產品備案/進口方式/宣稱限制，再建議平台和內容節奏。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__Searange Houseware Limited 20250407.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "1.期望能从众多平台中找出适合我们发展的平台并开展业务。 2.加入抖音，小红书，微信小程序，具体操作步骤及注意事项。",
    "story_selling_points": "SEARANGE 專注於家居玻璃製品。將歐洲時尚的玻璃飾品引入中國, 積極推廣歐尚生活格調. | | 多多熊DeDo Bear以食品為主，把來自印度尼西亞，菲律賓，中國及其他國家的安全特式食品引入香港和內地市場。我們的經營理念是不斷為大家帶來優質健康的食品體驗。 | | Chewy Ginger 是代理品牌，英倫風味禮盒裝薑糖，採用當地特有的新鮮生薑加工製作而成 。"
  },
  {
    "lead_id": "TDC2025-015",
    "program_year": 2025,
    "company": "Sino-Rate Enterprises Limited",
    "chinese_name": "僑力企業有限公司",
    "industry_group": "玩具/教育玩具",
    "product_category": "collectibles",
    "brand": "Honeybear",
    "contact": "Yui Chi Cheuk | 卓睿智",
    "title": "市場經理",
    "email": "hailey@sinorate.com",
    "phone": "3426 9182 | 9789 5694",
    "website": "",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "香港設計廊(京東國際): 設計廊 (honeybear蜜熊) 2022",
    "start_time": "2022",
    "target_customer": "",
    "pain_points": "品牌知名度不夠 日本官方定價較高 日本目標客群為30-50歲女性; 在國內一般被定位是兒童玩具 國內多平替",
    "needs": "刺激銷售、增加知名度、增加銷售渠道 / 刺激銷售、增加知名度、增加銷售渠道",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "目標客群",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC2025客户__Sino-Rate Enterprises Limited 20250324.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "",
    "story_selling_points": "情緒陪伴小熊仔 | 小巧熊仔方便隨時攜帶 | 小熊仔有靈動的眼睛, 可眨眼; 底部有磁石可站立在金屬表面 | 手腳頭可轉動, 熊仔表面有軟軟的植毛, 增添可愛感"
  },
  {
    "lead_id": "TDC2025-016",
    "program_year": 2025,
    "company": "Kong Fung Development Company",
    "chinese_name": "港豐發展公司",
    "industry_group": "其他消費品",
    "product_category": "",
    "brand": "",
    "contact": "Yiu Man Ng / 伍耀文",
    "title": "Manager",
    "email": "romanng19@gmail.com",
    "phone": "6996 3336",
    "website": "N/A",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "沒有",
    "start_time": "",
    "target_customer": "",
    "pain_points": "未見填寫",
    "needs": "增加銷售渠道",
    "service_segment": "A2 從零入場/開店搭建",
    "recommended_services": "OPM/平台代運營診斷",
    "data_completeness": "Medium",
    "data_score": 3,
    "stage_score": 4,
    "fit_score": 4,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "90-Day Market Entry Sprint",
    "email_subject": "跟進香港好物節諮詢：90日內地電商入場方案",
    "personalization_hook": "您目前處於準備或剛入場階段，重點是先選對主推SKU、平台和最低可行測試預算。",
    "cta_next_action": "安排20分鐘確認主推SKU、入場方式和預算，我們可整理一版90日路線圖。",
    "missing_data": "主推SKU/品牌/產品類別；目標客群",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC2025客户/Kong Fung Development Company (no mainland online shop) 20250327 (P.1/P.2).jpg",
    "source_confidence": "Medium",
    "consulting_expectations": "更深入了解內地電商情況",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2025-017",
    "program_year": 2025,
    "company": "Organic Mama Ltd",
    "chinese_name": "有機農社有限公司",
    "industry_group": "醫藥/保健品",
    "product_category": "健康產品",
    "brand": "TRIMTone / BODYMAX / OEM-ODM products",
    "contact": "Kylie Ngor",
    "title": "Director",
    "email": "kylie@organicmama.com.hk",
    "phone": "2575 1688 / 9268 9646",
    "website": "www.organicmama.com.hk",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "香港設計廊(京東國際) (2025)",
    "start_time": "2025年（手寫年份）",
    "target_customer": "",
    "pain_points": "希望了解如何運作京東國際/直播/平台合作，並找到可信任的國內合作伙伴；手寫內容部分需覆核。",
    "needs": "希望增加產品知名度，增加銷售渠道。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立",
    "data_completeness": "Medium",
    "data_score": 3,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "目標客群",
    "source_file": "Users/ricky/Downloads/TDC2026客户/TDC2025客户/Organic Mama Ltd 20250327.pdf",
    "source_confidence": "Medium",
    "consulting_expectations": "希望聽到/學會一些可行、公司可負擔的方案。",
    "story_selling_points": "從事健康產品約18年，主打健康飲食、減肥/瘦身、改善亞健康等方向；部分手寫內容需覆核。"
  },
  {
    "lead_id": "TDC2025-018",
    "program_year": 2025,
    "company": "3DP Technology Limited",
    "chinese_name": "3維打印科技有限公司",
    "industry_group": "美容/個人護理",
    "product_category": "直髮夾 (夾板/美髮夾/Hair Straightener)",
    "brand": "IseIse (自家品牌)",
    "contact": "Jonathan Chiu | 趙俊明",
    "title": "",
    "email": "jonathanchiu@3dptechgroup.com",
    "phone": "6907 7603",
    "website": "",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "抖音: 亮點至尊美髮電器用品 (待改名) 2025",
    "start_time": "2025年衫",
    "target_customer": "15~ 45歲 女士",
    "pain_points": "品牌缺乏知名度 (自家原創品牌) 用家難以區分技術特點 (MHM發熱技術為我司首創, 市場上主流為MCH及PTC發熱技術) 價格定位, 較一般國產無品牌, 小品牌貴 缺乏曝光度, 目前並無任何種草或koc, kol合作",
    "needs": "增加知名度 增加銷售渠道 / 增加銷售渠道 直接了解市場需求 / 直接了解市場需求",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__3DP Technology Limited 20250403.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "了解國內電商平台的生態 協助產品尋找合適定價",
    "story_selling_points": "我們相信，美髮不應以犧牲髮質為代價。 IseIse 透過精準溫度控制技術，讓造型同時兼顧護髮，提供消費者 低溫塑型、減少熱傷害、維持秀髮健康光澤的全新選擇。我們的產品不僅是造型工具，更是呵護髮質的智慧夥伴。傳統直髮夾溫度忽冷忽熱，導致秀髮受損？ StyloFlow採用 MHM均勻加熱技術，搭載 高精度溫控晶片，每秒進行1000次微調溫度，確保造型過程中溫度穩定，讓秀發免受過熱傷害，即使在 低溫（160°C - 180°C） 也能輕鬆塑型，減少髮絲水分流失，保持健康亮澤！ | | 搭配 陶瓷塗層浮動夾板，造型順滑不卡發，從此告別毛躁與熱損傷！"
  },
  {
    "lead_id": "TDC2025-019",
    "program_year": 2025,
    "company": "Alcolear Limited",
    "chinese_name": "光耀清醇生物科技有限公司",
    "industry_group": "食品飲品",
    "product_category": "營養補充劑",
    "brand": "Alcolear® 乾啦®",
    "contact": "Sek Lun Law | 羅錫麟",
    "title": "",
    "email": "alan@alcolear.com",
    "phone": "3168 7407 | 9565 2049",
    "website": "alcolear.com",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "",
    "start_time": "2025年2月",
    "target_customer": "喜歡喝酒，或不能避免喝酒，但又關注肝臟健康的人士",
    "pain_points": "競爭者眾多，但他們其實並沒有即時效果 公司並沒有太大資源在中國內地做廣告 公司沒有資源做視頻廣告 需要讓錶客戶群，得悉我們產品是有科研實證有效",
    "needs": "增加知名度 刺激國內銷售 / 刺激國內銷售",
    "service_segment": "A2 從零入場/開店搭建",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 4,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "90-Day Market Entry Sprint",
    "email_subject": "跟進香港好物節諮詢：90日內地電商入場方案",
    "personalization_hook": "您目前處於準備或剛入場階段，重點是先選對主推SKU、平台和最低可行測試預算。",
    "cta_next_action": "安排20分鐘確認主推SKU、入場方式和預算，我們可整理一版90日路線圖。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Alcolear Limited 20250324.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "希望能提供一些有效而又不需要太大資金投入的宣傳推廣方法 希望能向我們介紹一些有實力的網紅，幫助推廣我們的產品",
    "story_selling_points": "乾啦®是新一代的解酒护肝健康食品，内含ADH及ALDH双酶，帮助你击退头痛、宿醉，亦能有效缓解亚洲红脸症，解酒同时护肝，让你渡过美好的晚上，带来精神饱满的一天！"
  },
  {
    "lead_id": "TDC2025-020",
    "program_year": 2025,
    "company": "Aqua Monster Sports Company Limited",
    "chinese_name": "",
    "industry_group": "運動/戶外",
    "product_category": "水上運動用品",
    "brand": "Aqua Monster Sports Company Limited",
    "contact": "Jay Yeung / 楊慧如",
    "title": "Operation Director",
    "email": "aquamonstersports@gmail.com",
    "phone": "6732 6338",
    "website": "www.aquamonster.co",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "香港設計廊(京東國際): Aqua Monster (2025)；淘寶/天貓: 天鯊易購 (2025)",
    "start_time": "2025",
    "target_customer": "小朋友、成人",
    "pain_points": "內地同類競爭激烈；短視頻及平台內容化不足；希望把產品優勢更清楚地呈現給內地消費者。手寫內容部分需覆核。",
    "needs": "刺激銷售、增加知名度、增加銷售渠道。手寫內容部分需覆核。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立",
    "data_completeness": "Medium",
    "data_score": 3,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Aqua Monster Sports Company Limited 20250326.pdf.txt",
    "source_confidence": "Medium",
    "consulting_expectations": "希望了解可行做法，並得到清晰的營運理解及持續建議。",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2025-021",
    "program_year": 2025,
    "company": "BORD Limited",
    "chinese_name": "廣東博知寵物有限公司",
    "industry_group": "寵物用品",
    "product_category": "冷凍寵物生肉糧",
    "brand": "BORDHK",
    "contact": "Deon Au / 區翠嫻",
    "title": "總裁",
    "email": "deonau@bo-rd.com",
    "phone": "9156 9200",
    "website": "www.bo-rd.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "小紅書商城；微信",
    "start_time": "2024年9月",
    "target_customer": "中港澳的高端市場",
    "pain_points": "內地缺乏知名度；品牌形象不牢固；缺乏內地寵物主人成功案例背書；缺乏有生骨肉/鮮食餵飼經驗的分銷/零售/KOL。",
    "needs": "刺激銷售、增加知名度、增加銷售渠道。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__BORD Limited 20250320.pdf.txt",
    "source_confidence": "High",
    "consulting_expectations": "用最少資金刺激銷售、增加知名度、增加銷售渠道。",
    "story_selling_points": "創自 2014 年中國香港生肉糧品牌 BORD。十五年生肉餵養經驗和十年 | 與紐西蘭代工廠合作關係，令 BORDHK 國產產品透過中國海關官方出口 | 檢疫，獲中國海關簽發獸醫衛生證書，已從中國海關官方正規報關出口港 | 澳。"
  },
  {
    "lead_id": "TDC2025-022",
    "program_year": 2025,
    "company": "Concord Alliance Global Limited",
    "chinese_name": "康盟環球有限公司",
    "industry_group": "醫藥/保健品",
    "product_category": "保健品",
    "brand": "日本命力",
    "contact": "Ka Yiu Kwok | 郭嘉銚",
    "title": "",
    "email": "arielkwok@meiriki-jp.com.hk",
    "phone": "2194 0083 | 6633 1054",
    "website": "meiriki-jp.com.hk",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "",
    "start_time": "疫情期間",
    "target_customer": "用心經營27年，在香港、澳門、國內甚至海外都有忠實的支持者。",
    "pain_points": "想更精準投放廣告, 打開品牌在國內的知名度, 刺激銷失",
    "needs": "以上皆是",
    "service_segment": "B1 合規重類目入場",
    "recommended_services": "合規/跨境入場路線；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 5,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Compliance-Led Market Entry",
    "email_subject": "跟進香港好物節諮詢：合規類目入場與內容邊界",
    "personalization_hook": "您的品類涉及保健、酒類、食品或個護宣稱，入場前需要同時處理平台、內容和合規邊界。",
    "cta_next_action": "先確認產品備案/進口方式/宣稱限制，再建議平台和內容節奏。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Concord Alliance Global Limited 20250326.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "期望能分享更多香港保健品品牌成功的經驗",
    "story_selling_points": "日本命力投入了大量資源在新產品的科研和開發上，以確保產品質素達到最高要求。因此，他們尋找日本最高質素要求及符合日本厚生省GMP規格的廠房進行生產。為了實踐「優質、安全、有效」的承諾，日本命力從產品的原材料，到每一個生產程序，以至包裝運送，都經過嚴格監控。"
  },
  {
    "lead_id": "TDC2025-023",
    "program_year": 2025,
    "company": "Gosu Holding Limited",
    "chinese_name": "",
    "industry_group": "玩具/教育玩具",
    "product_category": "寵物玩具",
    "brand": "Zooahpet",
    "contact": "Louis Yung | 容熙健",
    "title": "",
    "email": "louisyung@gosu.com.hk",
    "phone": "6188 6155",
    "website": "www.gosu.com.hk / www.gmpets.com.hk",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "",
    "start_time": "2025",
    "target_customer": "貓咪飼主：對於擁有貓咪的家庭和個人，這是主要的目標客戶。他們尋找能夠增強貓咪生活品質的玩具和用品，以提供貓咪充分的娛樂和運動。 | 寵物零售商：包括寵物店、電商平台和專業的寵物用品經銷商，這些商家尋求提供多樣化的高品質產品來吸引顧客。",
    "pain_points": "不認識內地市場, 資金限制",
    "needs": "1. 提高知名度,利用社交媒體營銷,嘗試與網紅合作及參加展會和活動 | 2. 刺激銷售,透過限時優惠和促銷活動：定期舉辦促銷活動，如滿額減免、打折等，吸引消費者購買。 | 3. 增加銷售渠道,如開設網店,在如 淘寶、京東等主要電商平台開設官方旗艦店，增加品牌的可見性和可獲得性,此外嘗試本地化合作：與當地的零售商合作，將產品放在實體店銷售，讓顧客能夠直接接觸和體驗產品。 | 4. 數據分析和反饋,根據消費者行為分析：利用數據分析工具，了解消費者的購買習慣和偏好，從而調整營銷策略和產品供應。",
    "service_segment": "A2 從零入場/開店搭建",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 4,
    "fit_score": 4,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "90-Day Market Entry Sprint",
    "email_subject": "跟進香港好物節諮詢：90日內地電商入場方案",
    "personalization_hook": "您目前處於準備或剛入場階段，重點是先選對主推SKU、平台和最低可行測試預算。",
    "cta_next_action": "安排20分鐘確認主推SKU、入場方式和預算，我們可整理一版90日路線圖。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Gosu Holding Limited (no mainland online shop) 20250320.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "認識更多",
    "story_selling_points": "ZOOAHPET 是一個專注於提供高品質貓玩具的品牌,100% 韓國制做 | 主要產品包括： | 長杆玩具 (約 1 米長)：這種玩具適合與貓咪互動，杆身彈性極高,安全,能有效刺激牠們的狩獵本能。 | 線杆玩具 (約 1.8 米長)：這個玩具可自由伸縮,增加靈活性。 | 小型線杆玩具 (約 63 厘米長)：適合空間有限的環境，依然能給予貓咪足夠的玩樂。 | 貓用補充玩具：這些玩具設計上可以輕鬆更換，延長玩具的使用壽命，並且保持貓咪的新鮮感。"
  },
  {
    "lead_id": "TDC2025-024",
    "program_year": 2025,
    "company": "Herb Standard Company Limited",
    "chinese_name": "正品藥業有限公司",
    "industry_group": "食品飲品",
    "product_category": "健康食品",
    "brand": "炎痛消、正品Herbstandard、維再生等等",
    "contact": "Thomas Li | 李寶文",
    "title": "",
    "email": "thomasli@herbstandard.com.hk",
    "phone": "3997 0506 | 6231 4008",
    "website": "www.herbstandard.com.hk",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "淘寶/天貓: HerbStandard海外旗舰店 2024；小紅書商城: 正品 Herb Standard (小红书号：26348103871) 2024",
    "start_time": "2024年年中",
    "target_customer": "幼兒至老人家",
    "pain_points": "運輸物流、品牌知名度等等",
    "needs": "刺激銷售、增加知名度、增加銷售渠道",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；合規/跨境入場路線；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Herb Standard Company Limited 20250407.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "希望政府可以帶頭支持或就健康食品類與內地部門磋商，有關豁免等等方向。",
    "story_selling_points": "《正品藥業》於2011年創立，以「專業、創新、嚴謹」為公司定位，致力搜羅世界各地優質及地道的原材料，揉合中西醫學思維及實證，提供多元化健康產品，照顧香港每一個家庭；關懷每一位香港人所需。 | 《正品藥業》高度重視產品的質量與安全，確保由挑選原材料來源地至生產流程，每一步都符合或高於政府規定的安全標準，堅守承諾將最高質素的健康產品帶給您。進口產品是由國際機構頒發的GMP及HACCP認證的廠房生產，確保在製造過程中品質穩定性及安全性，符合嚴格的管理標準。確保100%安全可靠，絕無西藥成分、無副作用及不依賴。"
  },
  {
    "lead_id": "TDC2025-025",
    "program_year": 2025,
    "company": "Herbs Generation International Ltd",
    "chinese_name": "草姬集團控股有限公司",
    "industry_group": "醫藥/保健品",
    "product_category": "保健品",
    "brand": "草姬",
    "contact": "Edgar Ng | 吳兆徽",
    "title": "",
    "email": "edgarng@herbs.hk",
    "phone": "2356 0361 | 6015 5632",
    "website": "https: / herbs.hk/ | https: / www.zinomall.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "抖音: HERBS草姬海外旗舰店 | 草本健康品牌草姬 2024 | 2025；淘寶/天貓: herbs草姬海外旗舰店 2019；京東/京東國際: HERBS草姬海外官方旗舰店 2024；小紅書商城: HERBS草姬海外旗舰店 2019",
    "start_time": "2019年",
    "target_customer": "大眾及對營養保健和健康意識關注的人士，",
    "pain_points": "品牌知名度不足，銷售未如理想。 私域版塊有難度 如何合適地選擇產品以合適受眾，以及爆款產品。",
    "needs": "刺激銷售、增加知名度、增加銷售渠道",
    "service_segment": "B1 合規重類目入場",
    "recommended_services": "OPM/平台代運營診斷；合規/跨境入場路線；品牌定位與信任建立；私域/CRM/復購",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Compliance-Led Market Entry",
    "email_subject": "跟進香港好物節諮詢：合規類目入場與內容邊界",
    "personalization_hook": "您的品類涉及保健、酒類、食品或個護宣稱，入場前需要同時處理平台、內容和合規邊界。",
    "cta_next_action": "先確認產品備案/進口方式/宣稱限制，再建議平台和內容節奏。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Herbs Generation International Ltd 20250407.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "增加品牌/ 產品知名度及銷售轉化",
    "story_selling_points": "草姬集團扎根香港超過20年，是多元保健品及美容與護膚品供應商。本集團於1999年由集團主席郭致因女士及郭晉安先生創立，經過25年努力經營，集團於2024年12月19日於香港聯合交易所主版上市。 | | 草姬產品結合中國傳統中醫學寶庫，及利用西方草藥及醫學標準，更配合現代尖端科技，研製出品質優良、安全可靠的現代中藥，及天然草本成份保健產品，讓都市人從日常生活中改善健康。 | | 草姬每一件產品都有嚴格要求，均經由取得GMP認證或其他國際標準化組織證書的藥廠進行研製，以確保我們產品的質素。品質檢測均交由獨立第三方進行，以確保產品符合香港有關的安全標準。"
  },
  {
    "lead_id": "TDC2025-026",
    "program_year": 2025,
    "company": "Ho Wa Sporting Goods Company Ltd",
    "chinese_name": "豪華體育用品有限公司",
    "industry_group": "運動/戶外",
    "product_category": "體育用品, 戶外用品",
    "brand": "Osprey, Pacsafe, Mystery Ranch, Nanga",
    "contact": "Cindy Ng | 吳麗芳",
    "title": "",
    "email": "cindy@howa.com.hk",
    "phone": "2722 0241 | 6110 0341",
    "website": "www.howa.com.hk",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "淘寶/天貓: 沒有 2022；小紅書商城: 豪華體育用品 2024；微信: 豪華體育用品 2024",
    "start_time": "2022年",
    "target_customer": "國內人士",
    "pain_points": "產品同質化, 大品牌, 毛利低 標品易比較價格, 難有差異化 香港發內地物流成本高, 單量不多入包稅倉成本也高, 只可以引流到門市消費, 客群有限制",
    "needs": "刺激銷售",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；合規/跨境入場路線；品牌定位與信任建立；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Ho Wa Sporting Goods Company Ltd 20250408.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "希望盡快安排, 並可以提供針對性支援的落地方式",
    "story_selling_points": "提供大小國際性海外品牌, 當中包括不少特色藍海牌子, 性價比高, 同時我們以香港商家定期在舉辦不同類型戶外活動, 以兩地特色文化吸引國內客人到港消費"
  },
  {
    "lead_id": "TDC2025-027",
    "program_year": 2025,
    "company": "Jacobson Van Den Berg (China) Ltd",
    "chinese_name": "雅各臣貿易有限公司",
    "industry_group": "其他消費品",
    "product_category": "消毒產品",
    "brand": "JcoNAT",
    "contact": "Clarice Lam / 林一全",
    "title": "Brand Manager-business",
    "email": "claricelam@jvdb.com",
    "phone": "2828 9306 / 9368 3000",
    "website": "www.jconat.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "抖音: JcoNAT 官方海外旗艦店 (2025)；淘寶/天貓: JcoNAT 海外旗艦店 (2020)；小紅書商城: JcoNAT 海外旗艦店 (2024)",
    "start_time": "2020年",
    "target_customer": "所有人及寵物",
    "pain_points": "各電商平台宣傳灰甲功能時有敏感詞限制；需要增強視頻及文章內容吸引度。",
    "needs": "刺激銷售、增加知名度、增加銷售渠道。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Jacobson Van Den Berg (China) Ltd 20250327.pdf.txt",
    "source_confidence": "High",
    "consulting_expectations": "刺激銷售、增加知名度、增加銷售渠道。",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2025-028",
    "program_year": 2025,
    "company": "Lifestyle Asia Pacific Ltd",
    "chinese_name": "麗泰（亞太）有限公司",
    "industry_group": "美容/個人護理",
    "product_category": "未填寫",
    "brand": "未填寫",
    "contact": "Ellis Law / 羅景聰",
    "title": "Finance Manager",
    "email": "elaw@lifestyles.net",
    "phone": "2739 0020 / 6358 4752",
    "website": "www.lifestyles.net",
    "platform_stage": "準備/尚未正式開始",
    "mainland_platforms": "",
    "start_time": "未開始但國內已有客戶。",
    "target_customer": "",
    "pain_points": "良莠不齊，唁放心用，怕消錢，資金有限。",
    "needs": "刺激銷售、增加知名度",
    "service_segment": "A2 從零入場/開店搭建",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "Medium",
    "data_score": 3,
    "stage_score": 4,
    "fit_score": 4,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "90-Day Market Entry Sprint",
    "email_subject": "跟進香港好物節諮詢：90日內地電商入場方案",
    "personalization_hook": "您目前處於準備或剛入場階段，重點是先選對主推SKU、平台和最低可行測試預算。",
    "cta_next_action": "安排20分鐘確認主推SKU、入場方式和預算，我們可整理一版90日路線圖。",
    "missing_data": "產品類別、品牌、目標客群、主推SKU、價格、合規/平台限制、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Lifestyles Asia Pacific Ltd (no mainland online shop) 20230321.docx.txt",
    "source_confidence": "Medium",
    "consulting_expectations": "對電商加深認識，成功有效在可負擔情況下開扣市場。",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2025-029",
    "program_year": 2025,
    "company": "Natural Made Company Limited",
    "chinese_name": "",
    "industry_group": "玩具/教育玩具",
    "product_category": "玩具、嬰兒產品、潮玩玩具",
    "brand": "Natural Made",
    "contact": "Kenneth Lee",
    "title": "",
    "email": "kenneth@naturalmade.com.hk",
    "phone": "2865 1136 | 6502 8389 / 6790 0434 (whatspp)",
    "website": "www.naturalmade.com.hk",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "淘寶/天貓: 娜卓美 | https: / shop107922547.taobao.com/?spm=a21n57.shop_search.0.0.7361523c9Kg4VC 2020；其他: Natural Made",
    "start_time": "公司於2015年曾初步嘗試內地電商業務。經過公司重整後，我們於2024年以全新品牌Natural Made（包括IP：空空及波魯波魯）重新推出市場。",
    "target_customer": "",
    "pain_points": "目前最大的挑戰是作為新IP品牌，缺乏接觸新客群的經驗，尤其是在中國市場資源投放及營運策略方面較為陌生。今年8月將推出新產品，希望透過好物節推廣核心IP波魯波魯及次要IP空空。我們計劃以療癒風格結合港風元素（包括不同地區版本），在小紅書進行引流，但缺乏相應工具與有效策略的知識。因此，希望得到熟悉IP營運、能以低成本但高效益方式推廣的媒體與市場營銷專家的協助。未來兩年，公司計劃結合港風特色，在中國及香港市場發展更多周邊及玩具產品。因此，此次活動的KPI將成為品牌發展的重要指標。",
    "needs": "我們希望此次諮詢服務能提供詳細且實際的指導與建議，快速回覆並密切合作，透過諮詢服務，我們希望更深入理解政府機構、公關公司、自媒體合作模式，成功地將香港品牌推廣至中國內地。並且參考Labubu、Chikawa、MOMAX、CASETiFY等成功的香港本地品牌案例，利用中國龐大的電商網絡，健康地拓展品牌業務，最終建立成為國際知名品牌。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立；AI內容降本",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "目標客群",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Natural Made Company Limited 20250422.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "",
    "story_selling_points": "波魯波魯 (PoruPoru) 花獅子 | 產品類型：安撫巾、毛絨公仔、港風聯乘潮玩 | 種族：森林妖精 | 性格特點：勇敢、堅強、冷靜，雖尚未完全成熟，但勇於接受挑戰，充滿好奇心並熱衷探索新事物。尤其親近具有無限可能的小孩，會主動陪伴與保護他們。容易因小成功而自豪，遭遇挫折時會感到沮喪，但能迅速恢復。 | 發展策略：主線產品集中於兒童及親子類，副產品線推出具港風特色的周邊及日常用品，並透過Instagram與小紅書等社交媒體營運。 | | | 空空 | 產品類型：兒童玩具（空空2030太空工程穿梭機、空空2030太空工程運輸車） | 種族：人類 | 性格特點：身穿宇航服、頭戴大頭盔的太空人。對新事物充滿興趣，積極參與太空探索，雖喜愛可愛生物但態度謹慎。主動且積極給予別人鼓勵，認為讚賞是前進的動力。即使別人看不到他的表情，也總會用豎起拇指的動作表示肯定。 | 產品特色：以STEAM教育理念設計，著重訓練兒童手腕力量，包裝設計新穎有趣，融合未來感與潮玩元素。 | 目標客群：4歲以上學齡前兒童及家長"
  },
  {
    "lead_id": "TDC2025-030",
    "program_year": 2025,
    "company": "Nexus Industrial Design Limited",
    "chinese_name": "溢鋒設計有限公司",
    "industry_group": "家居/家電科技",
    "product_category": "电子闹钟, 彩色天氣預報時計, 大屏顯示电子钟, 多功能投影闹钟, 幻彩投影闹钟, 手机藍牙連接 自動下載時間等等",
    "brand": "NID",
    "contact": "Rebecca Kwok | 郭素平",
    "title": "",
    "email": "rebecca@nexus-design.com.hk",
    "phone": "2116 8236 | 9816 4314",
    "website": "www.nexus-design.com.hk",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "淘寶/天貓: niD 電子鈡 2012年；其他: 1688, PDD 併多多",
    "start_time": "2012年",
    "target_customer": "有居家生活品味的年輕人士",
    "pain_points": "流量不足導致曝光度不夠，銷售不佳",
    "needs": "刺激銷售，增加知名度",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Nexus Industrial Design Limited 20250327.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "針對產品及網站運營提出改善建議",
    "story_selling_points": "niD 電子鈡"
  },
  {
    "lead_id": "TDC2025-031",
    "program_year": 2025,
    "company": "PP Laboratory Limited",
    "chinese_name": "寵研科技有限公司",
    "industry_group": "寵物用品",
    "product_category": "寵物用品",
    "brand": "PP Laboratory",
    "contact": "Cheuk Chi Luk | 陸卓知",
    "title": "",
    "email": "mandyluk@pplab.com.hk",
    "phone": "2460 3612 | 6016 7767",
    "website": "pplab.com.hk",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "小紅書商城: PP_Laboratory 2024",
    "start_time": "2024年十月",
    "target_customer": "Demographics: 26-35+, professional, educated, tech-ready | Psychographics: Value Functionality, Quality, Cares about self image, Expects customer service (knowledge from staff)",
    "pain_points": "產品主打中高端市場, 定價較一般內地寵物玩具高, 所以銷售量偏低 必須花費靠網紅種草先有大量曝光 內容方向不明確",
    "needs": "刺激銷售、增加知名度、增加線下銷售渠道",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；內容/KOL/KOC增長；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 5,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__PP Laboratory Limited 20250326.docx.txt",
    "source_confidence": "High",
    "consulting_expectations": "有效提高銷售及知名度 提供建議關於推廣上的政府資助, 初創沒太多資金, 而內地又必須花費大量金錢先有曝光",
    "story_selling_points": "For pet parents who see their pets as lifelong | companions, PP Lab is the wellness-driven lifestyle | brand that creates thoughtful, safe, and ergonomic | solutions — because every moment with your pet | deserves to last a lifetime."
  },
  {
    "lead_id": "TDC2025-032",
    "program_year": 2025,
    "company": "The Elias Enterprise Limited",
    "chinese_name": "僑梓企業有限公司",
    "industry_group": "食品飲品",
    "product_category": "傳統滋補品/方便頓養系列/滴雞精/漢方養生茶/湯",
    "brand": "中僑參茸",
    "contact": "Juliet Wong / 黃偉伶",
    "title": "Secretary",
    "email": "juliet.wong@chongkio.com",
    "phone": "3106 0860 / 9194 6977",
    "website": "www.chongkio.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "小紅書商城: 中僑參茸 (Mar. 2019)；微信: 中僑參茸 (Apr. 2020)；自家網站: https://www.chongkio.com/tc/index (Nov. 2024)",
    "start_time": "2022（天貓）",
    "target_customer": "注重身體健康、保健及對中成藥有興趣之人士",
    "pain_points": "內地電商市場發展迅速，香港中小企較難掌握箇中竅門。",
    "needs": "刺激銷售、增加知名度。",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__The Elias Enterprise Limited 20250325.pdf.txt",
    "source_confidence": "High",
    "consulting_expectations": "希望營業部同事更清楚了解如何將公司產品成功帶進國內市場。",
    "story_selling_points": ""
  },
  {
    "lead_id": "TDC2025-033",
    "program_year": 2025,
    "company": "Varicraft Company Limited",
    "chinese_name": "利家富有限公司",
    "industry_group": "家居/家電科技",
    "product_category": "環保產品 - 家品",
    "brand": "-1 Degree",
    "contact": "Tracy Li | 李麗芳",
    "title": "",
    "email": "account@varicraft.com",
    "phone": "2601 0933 | 9555 5188",
    "website": "(如有) | www.minus1degree.com",
    "platform_stage": "已有平台/待優化",
    "mainland_platforms": "香港設計廊(淘寶): | ☐ 其他 請註明： | ☐ 沒有",
    "start_time": "2025.02.14",
    "target_customer": "上班族, 時尚女性",
    "pain_points": "有無從入手的感覺, | 希望藉香港設計廊(京東國際) 及 香港好物節 帶品牌入內地市場 及 了解內地電商市場運作",
    "needs": "（例如：刺激銷售、增加知名度、增加銷售渠道等） | 開拓內地市場, | 打開品牌知名度",
    "service_segment": "A1 已有平台增長/OPM",
    "recommended_services": "OPM/平台代運營診斷；品牌定位與信任建立",
    "data_completeness": "High",
    "data_score": 5,
    "stage_score": 5,
    "fit_score": 5,
    "urgency_score": 3,
    "outreach_status": "Ready for outreach",
    "campaign": "Existing Platform Growth Audit",
    "email_subject": "跟進香港好物節諮詢：平台增長與OPM營運診斷",
    "personalization_hook": "您已經有內地平台基礎，第一步可先用平台數據找出流量、內容、轉化和復購的瓶頸。",
    "cta_next_action": "安排20分鐘確認近3-6個月平台數據，回覆後可先給一頁診斷清單。",
    "missing_data": "平台數據、投放成本、主推SKU、90日預算",
    "source_file": "Users/ricky/Documents/Codex/2026-07-14/s/work/tdc_crm_extract/TDC客户2025（2）__Varicraft Company Limited 20250327.doc.txt",
    "source_confidence": "High",
    "consulting_expectations": "建議合適銷售渠道 | 推廣策略",
    "story_selling_points": "[品牌故事] 藉著提供價格合理、時尚和耐用的產品再加上簡單的創意，鼓勵更多人嘗試開始綠色生活。 -1度聽起來不多，但在日常生活減少一定程度的碳足跡，意義十分重大。 | [產品賣點] 環保食物袋是一循環再用的食物盒可以取替一次性飯盒，適合盛載食物(固體/液體)的收納袋，配有手挽, 方便外帶,不必用袋中袋的方式攜帶,更符合環保。袋身設計上闊下窄, 加上袋口可隨意外翻, 方便進食. 環保食物袋能曲摺疊, 便於外帶收納."
  }
];
